version: "3.7"
services:
  database:
    image: postgres:12-alpine
    ports:
      - "59001:5432"
    volumes:
      - .:/app:cached
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    working_dir: /app
    environment:
      - POSTGRES_INITDB_ARGS="--no-locale"
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=superuserpass
      - POSTGRES_DB=ts-db

    restart: always
