import { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();
  const { parama, paramb } = router.query;
  return (
    <div className={styles.container}>
      <Head>
        <title>Redirected</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title2}>Redirected</h1>

        <p>paramA: {parama}</p>
        <p>paramB: {paramb}</p>
      </main>
    </div>
  );
};

export default Home;
