import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";
import { useRef, MouseEvent } from "react";
import { useQuery } from "@tanstack/react-query";

type Response = {
  parama: string;
  paramb: string;
};

const Home: NextPage = () => {
  const formRef = useRef<HTMLFormElement>(null);

  const { data, refetch } = useQuery({
    enabled: false,
    queryKey: ["refetch-render"],
    queryFn: async () => {
      const response = await fetch("/api/refetch-render");
      return response.json() as Promise<Response>;
    },
  });
  const parama = data?.parama;
  const paramb = data?.paramb;

  const handleClick = async (e: MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    await refetch();

    if (formRef.current) {
      formRef.current.submit();
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Refetch Render</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Refetch Render</h1>
        <p>parama: {parama}</p>
        <p>paramb: {paramb}</p>
        <form
          method="POST"
          action={"/api/refetch-render"}
          ref={formRef}
          target="_blank"
        >
          <input type="hidden" name="parama" value={parama} />
          <input type="hidden" name="paramb" value={paramb} />
          <button type="submit" onClick={handleClick}>
            Submit
          </button>
        </form>
      </main>
    </div>
  );
};

export default Home;
