name: Slack Notification by webhook on Workflow Dispatch

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "Message from GitHub Actions by webhook on Workflow Dispatch",
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
